spring.application.name=short-my-url

spring.datasource.url=jdbc:mysql://localhost:3306/shortmyurl
spring.datasource.username=root
spring.datasource.password=root
spring..jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

logging.level.root=INFO
logging.level.com.url.shortmyurl=DEBUG

jwt.secret=64bcd072b26dfeeadc8a44d441f4c937c00b7394a064730dda525f0c13557b78
jwt.expiration=17000000